### ISSUE TITLE
Would the store accept a plugin that requires a browser extension?

### ISSUE THREAD

**Issue by brigazvi** [Flow-Launcher/Flow.Launcher.PluginsManifest#429]
I want to develop a plugin that searches through the browser's open tabs.
I can't access the tab's data or switch between tabs from outside the browser.
So I need to develop a browser extension that will go along with the FL plugin.
I saw that node js dependencies should not be installed manually by the users, so I thought maybe browser extensions are a problem too. But I can't figure out a way to achieve this idea without it.

**Comment by jjw24** [comment]
That's fine, no issues.

You can approach installing the extension by:
1. Check after invoking the plugin whether extension is installed.
2. If not, prompt via a query result by either going to your readme with a section on installing the extension, or have a code to download and run the installation for the user.

I don't know which is the better approach in terms of user experience, so I would suggest option 1 just because option 2 may require user interaction plus handling installation status (success, failed or still in progress), that's some extra code you may or may not want to write yet.

**Comment by brigazvi** [comment]
Thank you for the detailed answer.
