### ISSUE TITLE
Install of standard plugins

### ISSUE THREAD

**Issue by hudlnrudln** [Flow-Launcher/Flow.Launcher.PluginsManifest#49]
I am able to uninstall standard plugins(calculator, bookmarks,...) but not to install them again.

**Comment by jjw24** [comment]
Sorry not sure what you mean, you are able to uninstall standard plugins, but unable to reinstall them?

**Comment by hudlnrudln** [comment]
Thanks for the answer!

yes i was able to uninstall the standard calculator plugin vi `<pm uninstall calculator>`
But when I am trying to reinstall it via `<pm install>` calculator is not avaiable in the list.
So now i am missing my most valuable plugin in flow launcher :(

**Comment by jjw24** [comment]
Oh lol ok, nah we don't publish standard plugins because they are already embedded with the install. 

What you can do, exit flow. 

if you have portable mode on then move your userdata folder out of the flow folder to somewhere safe.

Download and reinstall flow, this will bring back the standard plugins. 

Again if you were in portable mode then exit flow and move your userdata folder to the default install location, which is in %localappdata%\ , remmeber to delete the userdata there and move your own one in.

That should get you back up and running

**Comment by hudlnrudln** [comment]
ok thanks for the info!
Will try with reinstalling!

Maybe it would be good then to remove the standard apps from the uninstall list or only allow to deactivate.

by the way, thanks for the great app, highly appreciated ;)

**Comment by jjw24** [comment]
No worries. Enjoy
