### ISSUE TITLE
What's the difference between wox and flow？

### ISSUE THREAD

**Issue by wangkun19930608** [Flow-Launcher/Flow.Launcher.PluginsManifest#52]
Both are useful for me. But I still use Wox more often.Thank you very much.

**Comment by taooceros** [comment]
I suggest you migrate this issue to our main repo because this repo is for the community made Plugins record.

Basically, we have made a significant amount of improvement over wox recently. For example the acronym search.
Also, wox is not currently under active development, but we are. Our member are willing to respond and resolve issue from users.
If you would like to check out more information on our improvements, I suggest you to check out our release note (and the ongoing release pull request) in our main repo.

**Comment by jjw24** [comment]
closing this. @wangkun19930608 if you think there is something from Wox that is a good feature to add to Flow, be sure to put in an issue to let us know at https://github.com/Flow-Launcher/Flow.Launcher.
